[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "adb-client"
path = "src/main.rs"
[dependencies]
tokio = { version = "1", features = ["macros","fs","net"] }



